server:

  port: ${SERVER_PORT}

  servlet:
    context-path: ${PROJECT_API}

spring:
  application:
    name: ${PROJECT_NAME}

feign:
  client:
    config:
      user-service:
        url: ${FEIGN_CLIENT_CONFIG_USER_SERVICE_URL}